name = "artemis"
description = "A lunar-themed digital garden framework for Zola"
license = "MIT"
min_version = "0.16.0"

# The original theme creator
[original]
name = "not-matthias"
homepage = "https://not-matthias.github.io"
repo = "https://github.com/not-matthias/apollo"

# Your information as the creator of Artemis
[author]
name = "alex"
homepage = "https://nonmodernist.com"

# Features your theme supports
[extra]
# These are just suggestions based on what I've seen in your files
moon_phases = true
pixel_borders = true
og_emoji_support = true
section_dividers = true
backlinks = true